### ISSUE TITLE
Suppress warnings

### ISSUE THREAD

**Issue by cdeutsch** [AndrewLeedham/vscode-css-modules#1]
I know extension is just for syntax highlighting, but any idea where to start on suppressing `Unknown property: 'composes'` warnings?

![image](https://user-images.githubusercontent.com/404765/38527572-0bc28c36-3c21-11e8-977c-3d9d34269470.png)

Thanks!

**Comment by AndrewLeedham** [comment]
The quick and dirty fix is turning of VSCode's validation using `"css.validate": false`. Alternatively you could just suppress unknown property warnings using `"css.lint.unknownProperties": "ignore"`. Neither are ideal, but for now they're the only solutions I am aware of.

**Comment by cdeutsch** [comment]
That helps! Thanks!!

**Comment by EwenDC** [comment]
I don't know if Andrew can add this to the plugin itself, but if you want to get rid of the warning without disabling linting, you can now add the following line to your settings.json file in the .vscode folder of your project:
`"scss.lint.validProperties": ["composes"]`

That's for SCSS files specifically, but it works for all css linters. just change the "scss" to your style sheet language of choice like so:
`"css.lint.validProperties": ["composes"]`
`"less.lint.validProperties": ["composes"]`

**Comment by AndrewLeedham** [comment]
Thanks @EwenDC. I'll see if I can add it, not sure If I can set external settings, but I'll do some research. Will be a great addition to the extension 👍

**Comment by AndrewLeedham** [comment]
Unfortunately it doesn't look like this is possible. https://code.visualstudio.com/api/references/contribution-points#contributes.configurationDefaults looked promising but it only allows for editor settings.

I'll add a suggestion to add the settings to the README.

**Comment by AndrewLeedham** [comment]
Adding `validProperties` is now suggested in the README as of v1.1.4.
